Feat/post persistence
capsicum-annuum/api pull request #20
Opened 2020-05-10 01:04 UTC by GabrielTamujo

- Criado a modelagem/persistência do cadastro de novos movimentos.

- Cada movimento possui uma lista de Necessidades, onde especificasse a Skill desejada, tal como a Disponibilidade necessária - para necessidades materiais, a a disponibilidade deverá ser nula e a skill deverá ser "Doador". 

- Junto ao objeto que representa a Necessidade, está associada uma lista de candidaturas, representando todos os usuários que se apresentaram para ajudar. Tal como a lista dos voluntários que foram selecionados para ajudar.

- Foi criado uma Annotation Customizada para validar as datas informadas para o evento do novo movimento.

2020-05-11 01:47 UTC, lhendges approved these changes

2020-05-16 23:10 UTC, robsonrosa requested changes

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/validator/DateStartBeforeDateEndValidator.java
> +public class DateStartBeforeDateEndValidator implements ConstraintValidator<DateStartBeforeDateEnd, Movement> {
Acho que seria melhor usar uma interface como "Interval" ou "Duration", possuindo as duas datas e Movement implementa essa interface, de modo que essa validação pode ser usada em mais lugares.

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/request/MovementRequest.java
> +    @NotEmpty(message = "A lista de Causas não pode estar vazia.")
Lista de necessidades

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/request/MovementRequest.java
> +    private List<String> causeThatSupport;
Por que String? Não deveria ter o id das causas?

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/request/NeedRequest.java
> +    private String skill;
Não deveria ser o Id da Skill?

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/request/NeedRequest.java
> +    @NotNull(message = "O id do usuário autor não pode ser nulo.")
Mensagem errada

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/request/UserOrganizationRequest.java
> +    private String twitterUrl;
Por enquanto ok, mas fica um débito técnico pra ter uma lista de mídias pra não precisar aumentar a tabela horizontalmente.

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/request/UserVolunteerRequest.java
> +    private String twitterUrl;
Por enquanto ok, mas fica um débito técnico pra ter uma lista de mídias pra não precisar aumentar a tabela horizontalmente.

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/domain/Need.java
> +    @ManyToMany
Não seria oneToMany aqui?

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/domain/Need.java
> +    private List<Volunteer> volunteers;
O que exatamente representa essa lista? Os voluntários não estão na Candidacy?

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/listener/AttributeEncodeListener.java
> +        } else if (entity instanceof Movement) {
Na minha opinião, cada Listener deveria resolver sua questão, ou seja, ter 3 listeners ao invés de 1 com 3 IF's. E dar preferência pro uso de interfaces ao invés de classes concretas. Talvez isso apsse assim, ams daí cadastra um débito técnico lá, por que ta estranho isso.

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/service/FindUserByIdService.java
> +            .orElseThrow(() -> new RegisterNotFoundException("User não encontrado!"));
Usuário, não User

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/service/SaveMovementService.java
> +        log.info("Start to create an UserOrganization for: '{}'", movementRequest);
"create an UserOrganization" ?

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/service/SaveMovementService.java
> +        final Address address = saveAddressService.saveAddress(movementRequest.getAddressRequest());
Esse "saveAdress" poderia ser apenas "save" né?

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/service/SaveNeedService.java
> +        final Skill skill = findSkillByDescriptionService.find(needRequest.getSkill());
Comentei lá no Request: acho que deveria vir o ID, até por que o front vai precisar listar as Skills pro cara selecionar, então o frot vai ter o ID delas.

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/service/SaveNeedService.java
> +        final Availability availability = new Availability();
Acho que poderia ter um Mapper pra isso né? Prevejo esse código sendo replicado num futuro próximo.

2020-05-16 23:10 UTC, robsonrosa commented on src/test/java/br/com/annuum/capsicum/api/service/SaveMovementServiceTest.java
> +        Mockito.verify(movementRepository, times(1)).save(expectedMovement);
Não ta considerando se tá salvando com as skills, cause e availability corretos.

2020-05-16 23:10 UTC, robsonrosa commented on src/test/java/br/com/annuum/capsicum/api/service/SaveMovementServiceTest.java
> +        Mockito.verify(movementRepository, times(1)).save(expectedMovement);
Não tá verificando se ta salvando as necessidades

2020-05-16 23:10 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/domain/Volunteer.java
> +public class Volunteer {
Achei esse nome muito ambígui! Muito confuso UserVolunteer e Volunteer. Algo relacionado à presença ou participação seria mais indicado. E Por que a sequence é "candidate"?

2020-05-22 00:49 UTC, robsonrosa requested changes

2020-05-22 00:49 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/domain/Movement.java
> +    private Long PictureId;
primeira letra deve ser minúscula

2020-05-22 00:49 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/domain/Need.java
> +    private Boolean isActive;
Sempre dê preferência pra usar ENUM, mesmo que sejam apenas duas opções. Motivação:

1. Por que ATIVO/INATIVO é mais semântico que true/false
1. Por que se a demanda mudar e ter status intermediários, precisará de um refactoring mais complexo

Mas fica como reflexão futura. Pode marcar como resolvido.

2020-05-22 01:21 UTC, robsonrosa approved these changes

2020-05-22 01:21 UTC, merged