Feat/list federated unity
capsicum-annuum/api pull request #25
Opened 2020-06-13 21:39 UTC by Lucas-Bertolini

- Criado feature de listagem de Estados
- Criado controller de `Locality`

2020-06-13 23:41 UTC, robsonrosa requested changes

2020-06-13 23:41 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/LocalityController.java
> +    @GetMapping("/federated-unities")
singular

2020-06-13 23:41 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/response/FederatedUnitiesListResponse.java
> +    List<FederatedUnityDto> federatedUnityList;
Não seguiu o mesmo padrão de "cities" e "causes"

2020-06-13 23:41 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/response/SkillListResponse.java
> +    List<SkillDto> skillList;
Não seguiu o mesmo padrão de "cities" e "causes"

2020-06-13 23:41 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/mapper/FederatedUnityMapper.java
> +public class FederatedUnityMapper {
Implementando o `br.com.annuum.capsicum.api.mapper.Mapper<IN, OUT>` não precisaria do map da lista

2020-06-13 23:41 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/repository/CityRepository.java
> +    @Query("SELECT new br.com.annuum.capsicum.api.domain.dto.CityDto(c.id, c.name) FROM City c " + "WHERE c.federatedUnity.id = ?1")
Por que tem essa concatenação de String?

2020-06-13 23:41 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/repository/CityRepository.java
> +    List<CityDto> retrieveAllCitiesAsCityDtoByFederatedUnity(Long idFederatedUnity);
O padrão que estamos usando é `findAll`

2020-06-13 23:41 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/service/FindAllCitiesByFederatedUnity.java
> +public class FindAllCitiesByFederatedUnity {
Duplicado em `FindAllCitiesByFederatedUnityService`

2020-06-13 23:41 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/service/FindAllFederatedUnityService.java
> +public class FindAllFederatedUnityService {
Não seguiu o padrão ` FindAllCities` no plural

2020-06-13 23:41 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/service/FindAllFederatedUnityService.java
> +        List<FederatedUnity> federatedUnities = (List<FederatedUnity>) federatedUnityRepository.findAll();
Não precisa desse cast se esse método for declarado no Repostiory

2020-06-13 23:42 UTC, GabrielTamujo commented on src/main/java/br/com/annuum/capsicum/api/controller/LocalityController.java
> +    @GetMapping("/federated-unities")
FindAllCity...?

2020-06-14 01:22 UTC, robsonrosa requested changes

2020-06-14 01:22 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/service/FindAllFederatedUnitiesService.java
> +            .setFederatedUnities((List<FederatedUnityDto>) federatedUnityMapper.map(federatedUnities));
Por que tem esse cast se eles são do mesmo tipo?

2020-06-14 01:29 UTC, robsonrosa approved these changes

2020-06-14 01:29 UTC, merged