Refactor/evaluation persistence
capsicum-annuum/api pull request #39
Opened 2020-07-04 15:27 UTC by GabrielTamujo

- Avaliação entre usuários

2020-07-06 12:00 UTC, robsonrosa requested changes

2020-07-06 12:00 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/request/MovementAuthorEvaluationRequest.java
> +    private Integer note;
Rating não seria melhor?

2020-07-06 12:00 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/request/VolunteerEvaluationRequest.java
> +    private Long idCandidacy;
No `MovementAuthorEvaluationRequest` tu usou `candidacyId`

2020-07-06 12:00 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/EvaluationController.java
> +    @PostMapping("/movement-author")
Achei confuso. Quem tá sendo avaliado é o movimento ou o autor do movimento? Será que dá pra tirar esse "author"?

2020-07-06 12:00 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/EvaluationController.java
> +public class EvaluationController {
Dúvida de Negócio: se eu participei desse movimento (sei lá, fui numa feira ou fui beneficiado por esse movimento), será que não seria legal poder avaliar tbm?

2020-07-06 12:00 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/request/VolunteerEvaluationRequest.java
> +    private Integer note;
@Min(value = 1, message = "A nota mínima deve ser 1")
    @Max(value = 5, message = "A nota máxima deve ser 5")

2020-07-06 12:00 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/request/MovementAuthorEvaluationRequest.java
> +    private Integer note;
@Min(value = 1, message = "A nota mínima deve ser 1")
    @Max(value = 5, message = "A nota máxima deve ser 5")

2020-07-06 12:00 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/controller/request/MovementAuthorEvaluationRequest.java
> +    private String feedback;
Definir um Size pra não zuar o banco.

2020-07-06 12:00 UTC, robsonrosa commented on src/main/java/br/com/annuum/capsicum/api/validator/SaveEvaluationValidator.java
> +            throw new AccessControlException("Não é possível avaliar um voluntário com status da candidatura diferente de PRESENT.");
Essa mensagem não vai ficar estranha quando estivermos valiando um movimento?

2020-07-17 00:11 UTC, GabrielTamujo commented on src/main/java/br/com/annuum/capsicum/api/controller/EvaluationController.java
> +    @PostMapping("/movement-author")
Pois é, inicialmente tinha pensado em avaliar o autor do movimento apenas... Que tu acha de adicionarmos uma classe extra de avaliação do movimento em si?

2020-07-17 00:18 UTC, GabrielTamujo commented on src/main/java/br/com/annuum/capsicum/api/controller/EvaluationController.java
> +public class EvaluationController {
É, acho que temos que criar uma classe extra de avaliação de um movimento... Só temos que definir bem essas regras pra controlar e liberar quem pode avaliar o movimento ou não (controlar no case se o cara realmente teve no evento ou não)... 
Um outra ideia sepa é a gente ter uns likes estilo facebook com status tipo "estive lá"/"amei" e um espaço pra comentários, aí a gente deixa isso livre pra qualquer pessoa interagir... Aí vai ser massa quando tu entrar na página da ONG, tu conseguir ver todos eventos realizados e a repercussão que teve, comentários/declarações e etc...

2020-07-25 22:32 UTC, merged